plugins = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/home/chad-yi/.hermes/workspace/mission-control-dashboard"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/data.json"

[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"
Pragma = "no-cache"
Expires = "0"

[[headers]]
for = "/*.json"

[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"